apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  namespace: appdev-kafka
  name: my-connect-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"  
spec:
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
    jmxhost: 0.0.0.0
    jmxport: 9999
  bootstrapServers: 'event-broker-dr-kafka-bootstrap.appdev-kafka.svc:9092'
  build:
    output:
      image: >-
        image-registry.openshift-image-registry.svc:5000/appdev-kafka/debezium-connect-postgres:1.9
      type: docker
    plugins:
      - name: postgres
        artifacts:
          - url: >-
              https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/1.9.0.Final/debezium-connector-postgres-1.9.0.Final-plugin.tar.gz
            type: tgz
  metricsConfig:
    type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        name: debezium-metrics
        key: debezium-metrics-config.yml
  version: 3.1.0
  replicas: 1
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: debezium-metrics
  labels:
    app: strimzi
data:
  debezium-metrics-config.yml: |
    startDelaySeconds: 0
    ssl: false
    lowercaseOutputName: false
    lowercaseOutputLabelNames: false
    rules:
    - pattern : "kafka.connect<type=connect-worker-metrics>([^:]+):"
      name: "kafka_connect_worker_metrics_$1"
    - pattern : "kafka.connect<type=connect-metrics, client-id=([^:]+)><>([^:]+)"
      name: "kafka_connect_metrics_$2"
      labels:
        client: "$1"
    - pattern: "debezium.([^:]+)<type=connector-metrics, context=([^,]+), server=([^,]+), key=([^>]+)><>RowsScanned"
      name: "debezium_metrics_RowsScanned"
      labels:
        plugin: "$1"
        name: "$3"
        context: "$2"
        table: "$4"
    - pattern: "debezium.([^:]+)<type=connector-metrics, context=([^,]+), server=([^>]+)>([^:]+)"
      name: "debezium_metrics_$4"
      labels:
        plugin: "$1"
        name: "$3"
        context: "$2"
