apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: inventory-connector  
  labels:
    strimzi.io/cluster: my-connect-cluster  
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  config:
    database.dbname: postgres
    database.hostname: postgres.appdev-kafka.svc
    database.password: XXXX
    database.port: 5432
    database.server.name: inventory
    database.user: postgres
  tasksMax: 1
