apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  namespace: appdev-kafka
  name: kafka-connect-jdbc
  annotations:
    strimzi.io/use-connector-resources: "true"  
spec:
  config:
    group.id: connect-cluster2
    offset.storage.topic: connect-cluster-offsets2
    config.storage.topic: connect-cluster-configs2
    status.storage.topic: connect-cluster-status2
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1    
  bootstrapServers: 'event-broker-dr-kafka-bootstrap.appdev-kafka.svc:9092'
  build:
    output:
      image: >-
        image-registry.openshift-image-registry.svc:5000/appdev-kafka/camel-sql-kafka-connect:0.11.5
      type: docker
    plugins:
      - name: jdbc
        artifacts:
          - url: >-
              http://httpd-example-appdev-kafka.apps.ocp4.quitala.eu/camel-sql-kafka-connector-0.11.5.tar.gz
            type: tgz

  version: 3.1.0
  replicas: 1
